// Autogenerated config

#ifndef STAPPLER_CONFIG_buildconfig_H_
#define STAPPLER_CONFIG_buildconfig_H_

#define MACOS 1
#define STAPPLER 1
#define DEBUG 1
#define MODULE_STAPPLER_FILESYSTEM 1
#define MODULE_STAPPLER_DATA 1
#define MODULE_STAPPLER_MAKEFILE 1
#define MODULE_STAPPLER_BUILD_DEBUG_MODULE 1
#define MODULE_STAPPLER_CORE 1

#ifdef __cplusplus
namespace stappler::buildconfig {
constexpr int STAPPLER_VERSION_API = 5;
constexpr int STAPPLER_VERSION_REV = 1;
constexpr int STAPPLER_VERSION_BUILD = 87;
constexpr auto MODULE_STAPPLER_FILESYSTEM_NAME = "stappler_filesystem";
constexpr auto MODULE_STAPPLER_DATA_NAME = "stappler_data";
constexpr auto MODULE_STAPPLER_MAKEFILE_NAME = "stappler_makefile";
constexpr auto MODULE_STAPPLER_BUILD_DEBUG_MODULE_NAME = "stappler_build_debug_module";
constexpr auto MODULE_STAPPLER_CORE_NAME = "stappler_core";
}

#endif // __cplusplus
#endif // STAPPLER_CONFIG_buildconfig_H_
