// Autogenerated config

#ifndef STAPPLER_CONFIG_appconfig_H_
#define STAPPLER_CONFIG_appconfig_H_


#ifdef __cplusplus
namespace stappler::appconfig {
constexpr int APPCONFIG_VERSION_VARIANT = 0;
constexpr int APPCONFIG_VERSION_API = 0;
constexpr int APPCONFIG_VERSION_REV = 0;
constexpr int APPCONFIG_VERSION_BUILD = 0;
constexpr int APPCONFIG_APP_PATH_COMMON = 0;
constexpr auto APPCONFIG_APP_NAME = "stappler-build";
constexpr auto APPCONFIG_BUNDLE_NAME = "org.stappler.stappler-build";
constexpr auto APPCONFIG_BUNDLE_PATH = "$EXEC_DIR:$CWD";
}

#endif // __cplusplus
#endif // STAPPLER_CONFIG_appconfig_H_
