// Autogenerated appconfig source

#include "stappler-appconfig.h"
#include "SPSharedModule.h"

namespace stappler::appconfig {
static SharedSymbol s_appconfigSharedSymbols[] = {
	SharedSymbol("APPCONFIG_VERSION_VARIANT", &APPCONFIG_VERSION_VARIANT),
	SharedSymbol("APPCONFIG_VERSION_API", &APPCONFIG_VERSION_API),
	SharedSymbol("APPCONFIG_VERSION_REV", &APPCONFIG_VERSION_REV),
	SharedSymbol("APPCONFIG_VERSION_BUILD", &APPCONFIG_VERSION_BUILD),
	SharedSymbol("APPCONFIG_APP_PATH_COMMON", &APPCONFIG_APP_PATH_COMMON),
	SharedSymbol("APPCONFIG_APP_NAME", APPCONFIG_APP_NAME),
	SharedSymbol("APPCONFIG_BUNDLE_NAME", APPCONFIG_BUNDLE_NAME),
	SharedSymbol("APPCONFIG_BUNDLE_PATH", APPCONFIG_BUNDLE_PATH),
};

static SharedModule s_bitmapSharedModule("appconfig", s_appconfigSharedSymbols, sizeof(s_appconfigSharedSymbols) / sizeof(SharedSymbol));

}

