#ifndef CORE_RUNTIME_INCLUDE_C_BITS_ATFILE_H_
#define CORE_RUNTIME_INCLUDE_C_BITS_ATFILE_H_

#define __SPRT_AT_FDCWD - 100
#define __SPRT_AT_SYMLINK_NOFOLLOW 0x100
#define __SPRT_AT_SYMLINK_FOLLOW 0x400
#define __SPRT_AT_NO_AUTOMOUNT 0x800
#define __SPRT_AT_EMPTY_PATH 0x1000
#define __SPRT_AT_STATX_SYNC_TYPE 0x6000
#define __SPRT_AT_STATX_SYNC_AS_STAT 0x0000
#define __SPRT_AT_STATX_FORCE_SYNC 0x2000
#define __SPRT_AT_STATX_DONT_SYNC 0x4000
#define __SPRT_AT_RECURSIVE 0x8000
#define __SPRT_AT_RENAME_NOREPLACE 0x0001
#define __SPRT_AT_RENAME_EXCHANGE 0x0002
#define __SPRT_AT_RENAME_WHITEOUT 0x0004
#define __SPRT_AT_EACCESS 0x200
#define __SPRT_AT_REMOVEDIR 0x200
#define __SPRT_AT_HANDLE_FID 0x200
#define __SPRT_AT_HANDLE_MNT_ID_UNIQUE 0x001

#endif // CORE_RUNTIME_INCLUDE_C_BITS_ATFILE_H_
