#ifndef CORE_RUNTIME_INCLUDE_C_BITS_SEEK_H_
#define CORE_RUNTIME_INCLUDE_C_BITS_SEEK_H_

#define __SPRT_SEEK_SET	0
#define __SPRT_SEEK_CUR	1
#define __SPRT_SEEK_END	2

#endif // CORE_RUNTIME_INCLUDE_C_BITS_SEEK_H_
