# Copyright (c) 2022 Roman Katuntsev <sbkarr@stappler.org>
# Copyright (c) 2023 Stappler LLC <admin@stappler.dev>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


ifdef LINUX

MODULE_STAPPLER_CRYPTO_GNUTLS_LIBS := -lgnutls -lnettle -lgmp -lhogweed
MODULE_STAPPLER_CRYPTO_GNUTLS_FLAGS :=
MODULE_STAPPLER_CRYPTO_GNUTLS_SRCS_DIRS :=
MODULE_STAPPLER_CRYPTO_GNUTLS_SRCS_OBJS :=
MODULE_STAPPLER_CRYPTO_GNUTLS_INCLUDES_DIRS :=
MODULE_STAPPLER_CRYPTO_GNUTLS_INCLUDES_OBJS :=
MODULE_STAPPLER_CRYPTO_GNUTLS_DEPENDS_ON :=

# module name resolution
MODULE_stappler_crypto_gnutls := MODULE_STAPPLER_CRYPTO_GNUTLS

endif


MODULE_STAPPLER_CRYPTO_OPENSSL_LIBS := -l:libgost.a -l:libssl.a -l:libcrypto.a -l:libz.a
MODULE_STAPPLER_CRYPTO_OPENSSL_FLAGS :=
MODULE_STAPPLER_CRYPTO_OPENSSL_SRCS_DIRS :=
MODULE_STAPPLER_CRYPTO_OPENSSL_SRCS_OBJS :=
MODULE_STAPPLER_CRYPTO_OPENSSL_INCLUDES_DIRS :=
MODULE_STAPPLER_CRYPTO_OPENSSL_INCLUDES_OBJS :=
MODULE_STAPPLER_CRYPTO_OPENSSL_DEPENDS_ON :=

# module name resolution
MODULE_stappler_crypto_openssl := MODULE_STAPPLER_CRYPTO_OPENSSL

ifdef LINUX
MODULE_STAPPLER_CRYPTO_OPENSSL_LIBS += -lpthread
endif

ifdef WIN32
MODULE_STAPPLER_CRYPTO_OPENSSL_LIBS += -lcrypt32 -ladvapi32 -luser32
endif


MODULE_STAPPLER_CRYPTO_MBEDTLS_LIBS := -l:libmbedtls.a -l:libmbedcrypto.a -l:libmbedx509.a
MODULE_STAPPLER_CRYPTO_MBEDTLS_FLAGS :=
MODULE_STAPPLER_CRYPTO_MBEDTLS_SRCS_DIRS :=
MODULE_STAPPLER_CRYPTO_MBEDTLS_SRCS_OBJS :=
MODULE_STAPPLER_CRYPTO_MBEDTLS_INCLUDES_DIRS :=
MODULE_STAPPLER_CRYPTO_MBEDTLS_INCLUDES_OBJS :=
MODULE_STAPPLER_CRYPTO_MBEDTLS_DEPENDS_ON :=

# module name resolution
MODULE_stappler_crypto_mbedtls := MODULE_STAPPLER_CRYPTO_MBEDTLS

ifdef WIN32
MODULE_STAPPLER_CRYPTO_MBEDTLS_LIBS += -lcrypt32 -ladvapi32
endif


MODULE_STAPPLER_CRYPTO_LIBS :=
MODULE_STAPPLER_CRYPTO_FLAGS :=
MODULE_STAPPLER_CRYPTO_SRCS_DIRS := $(STAPPLER_MODULE_DIR)/crypto
MODULE_STAPPLER_CRYPTO_SRCS_OBJS := 
MODULE_STAPPLER_CRYPTO_INCLUDES_DIRS :=
MODULE_STAPPLER_CRYPTO_INCLUDES_OBJS := $(STAPPLER_MODULE_DIR)/crypto
MODULE_STAPPLER_CRYPTO_DEPENDS_ON := stappler_crypto_$(STAPPLER_CRYPTO_DEFAULT) stappler_core

# module name resolution
MODULE_stappler_crypto := MODULE_STAPPLER_CRYPTO
